language: bash
services: docker

env:
  - VERSION=1.19.0 VARIANT=stretch
  - VERSION=1.19.0 VARIANT=jessie

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="rust:$VERSION${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
