language: rust
rust:
  - nightly
  - stable
  # The following Rust version represents the oldest supported version of Mio
  - 1.6.0

os:
  - linux
  - osx

script:
  - cargo test
  - cargo doc --no-deps

# Deploy documentation to S3 for specific branches. At some
# point, it would be nice to also support building docs for
# a specific tag
deploy:
  provider: s3
  access_key_id: AKIAIXM3KLI7WZS4ZA3Q
  secret_access_key:
    secure: g0E6fBvgTV+5RYecJqEa6qIrQfE6SnwQX9xA1mx2ISkKuIne8qgEfBFSLNeVywmOgl8Kv4gDgrt9OSm5vT8Kb4L2eAb5L7AUsnfpyLZMEPc6KevZEF1awS54vVY3E3ey3FjdZ/4bkMbiwiJTFcToy/MlHauD7oUDRGqz3SSZIt0=
  bucket: rustdoc
  endpoint: rust-doc.s3-website-us-east-1.amazonaws.com
  skip_cleanup: true
  local-dir: target/doc
  upload-dir: mio/${TRAVIS_BRANCH}
  acl: public_read
  on:
    condition: $TRAVIS_RUST_VERSION == "1.6.0" && $TRAVIS_OS_NAME == "linux"
    repo: carllerche/mio
    branch:
      - master
      - v0.5.x
      - v0.4.x
