[package]

name          = "mio"
version       = "0.3.6"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Lightweight non-blocking IO"
documentation = "http://rustdoc.s3-website-us-east-1.amazonaws.com/mio/v0.3.x/mio/"
homepage      = "https://github.com/carllerche/mio"
repository    = "https://github.com/carllerche/mio"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
log   = "0.3.1"
time  = "0.1.24"
bytes = "0.2.9"
slab  = "0.1.0"

[dependencies.nix]
git = "https://github.com/carllerche/nix-rust"

[dev-dependencies]
env_logger = "0.3.0"
tempdir    = "0.3.4"

[[test]]

name = "test"
path = "test/test.rs"
