[package]

name          = "mio"
version       = "0.6.0-dev"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Lightweight non-blocking IO"
documentation = "http://rustdoc.s3-website-us-east-1.amazonaws.com/mio/v0.5.x/mio/"
homepage      = "https://github.com/carllerche/mio"
repository    = "https://github.com/carllerche/mio"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
lazycell = "0.4.0"
log      = "0.3.1"
slab     = "0.3.0"
net2     = { version = "0.2.19", default-features = false }

[target.'cfg(unix)'.dependencies]
nix    = "0.6.0"
libc   = "0.2.4"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.1"
miow   = "0.1.3"
kernel32-sys = "0.2"

[dev-dependencies]
env_logger = "0.3.0"
tempdir    = "0.3.4"
bytes      = "0.3.0"

[[test]]
name = "test"
path = "test/mod.rs"
