[package]

name = "mio"
version = "0.0.1"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
time = "*"
log = "*"

[dependencies.nix]

git = "https://github.com/carllerche/nix-rust"

[dependencies]
bitflags = "0.1"

[[test]]

name = "test"
path = "test/test.rs"
