[package]

name          = "mio"
# When releasing to crates.io:
# - Update html_root_url.
# - Update CHANGELOG.md.
# - Update doc URL.
# - Create git tag
version       = "0.6.16"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Lightweight non-blocking IO"
documentation = "https://docs.rs/mio/0.6.16/mio/"
homepage      = "https://github.com/carllerche/mio"
repository    = "https://github.com/carllerche/mio"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
categories    = ["asynchronous"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
]

[features]
with-deprecated = []
default = ["with-deprecated"]

[dependencies]
iovec    = "0.1.2"
log      = "0.4"
net2     = { git = "https://github.com/redox-os/net2-rs" }
slab     = "0.4.0"

[target.'cfg(target_os = "fuchsia")'.dependencies]
fuchsia-zircon = "0.3.2"
fuchsia-zircon-sys = "0.3.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2.19"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.4"
miow   = { git = "https://github.com/redox-os/miow", branch = "latest" }

[dev-dependencies]
env_logger = { version = "0.4.0", default-features = false }
tempdir    = "0.3.4"
bytes      = "0.3.0"

[[test]]
name = "test"
path = "test/mod.rs"
